#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: fae1327921d4
#
Name     : kicad
Version  : 7.0.10
Release  : 1
URL      : https://gitlab.com/kicad/code/kicad/-/archive/7.0.10/kicad-7.0.10.tar.bz2
Source0  : https://gitlab.com/kicad/code/kicad/-/archive/7.0.10/kicad-7.0.10.tar.bz2
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : APSL-2.0 Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 CC-BY-SA-4.0 CC0-1.0 ClArtistic GPL-2.0 GPL-3.0 HPND ICU ISC MIT Zlib
Requires: kicad-bin = %{version}-%{release}
Requires: kicad-data = %{version}-%{release}
Requires: kicad-lib = %{version}-%{release}
Requires: kicad-license = %{version}-%{release}
Requires: kicad-locales = %{version}-%{release}
Requires: kicad-python = %{version}-%{release}
Requires: kicad-python3 = %{version}-%{release}
BuildRequires : OpenCASCADE-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : glew-dev
BuildRequires : glibc-dev
BuildRequires : glm-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(harfbuzz-icu)
BuildRequires : pkgconfig(libunwind-ptrace)
BuildRequires : pkgconfig(ngspice)
BuildRequires : pkgconfig(odbc)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pypi(pybind11)
BuildRequires : pypi-wxPython-python3
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : swig
BuildRequires : wxWidgets-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory will contain headers for the various types of
KiCad dynamic plugins and associated APIs.

%package bin
Summary: bin components for the kicad package.
Group: Binaries
Requires: kicad-data = %{version}-%{release}
Requires: kicad-license = %{version}-%{release}

%description bin
bin components for the kicad package.


%package data
Summary: data components for the kicad package.
Group: Data

%description data
data components for the kicad package.


%package dev
Summary: dev components for the kicad package.
Group: Development
Requires: kicad-lib = %{version}-%{release}
Requires: kicad-bin = %{version}-%{release}
Requires: kicad-data = %{version}-%{release}
Provides: kicad-devel = %{version}-%{release}
Requires: kicad = %{version}-%{release}

%description dev
dev components for the kicad package.


%package lib
Summary: lib components for the kicad package.
Group: Libraries
Requires: kicad-data = %{version}-%{release}
Requires: kicad-license = %{version}-%{release}

%description lib
lib components for the kicad package.


%package license
Summary: license components for the kicad package.
Group: Default

%description license
license components for the kicad package.


%package locales
Summary: locales components for the kicad package.
Group: Default

%description locales
locales components for the kicad package.


%package python
Summary: python components for the kicad package.
Group: Default
Requires: kicad-python3 = %{version}-%{release}

%description python
python components for the kicad package.


%package python3
Summary: python3 components for the kicad package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kicad package.


%prep
%setup -q -n kicad-7.0.10
cd %{_builddir}/kicad-7.0.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706125732
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake .. -DKICAD_BUILD_I18N=ON \
-DKICAD_BUILD_QA_TESTS=OFF \
-DKICAD_I18N_UNIX_STRICT_PATH=ON \
-DKICAD_INSTALL_DEMOS=ON \
-DKICAD_SCRIPTING_WXPYTHON=ON \
-DKICAD_USE_EGL=ON \
-DKICAD_USE_OCC=ON \
-DKICAD_VERSION_EXTRA=%{release}
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706125732
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kicad
cp %{_builddir}/kicad-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/kicad/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/kicad-%{version}/LICENSE.3-CLAUSE-BSD %{buildroot}/usr/share/package-licenses/kicad/534d2a4a032e36089b075fcea7c5fa824b68f2f6 || :
cp %{_builddir}/kicad-%{version}/LICENSE.APACHE-2.0 %{buildroot}/usr/share/package-licenses/kicad/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/kicad-%{version}/LICENSE.BOOSTv1_0 %{buildroot}/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/kicad-%{version}/LICENSE.CC-BY-SA-4.0 %{buildroot}/usr/share/package-licenses/kicad/8a1a0366d77ee3af93e9f1a6c5c14526be2d1e50 || :
cp %{_builddir}/kicad-%{version}/LICENSE.CC0 %{buildroot}/usr/share/package-licenses/kicad/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kicad-%{version}/LICENSE.GPLv3 %{buildroot}/usr/share/package-licenses/kicad/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/kicad-%{version}/LICENSE.ISC %{buildroot}/usr/share/package-licenses/kicad/5ade1f53777ddcabcbc4638e550155c97825db30 || :
cp %{_builddir}/kicad-%{version}/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/5d45b543b1c2f5b45a04c4140b961862fd74c6e1 || :
cp %{_builddir}/kicad-%{version}/thirdparty/argparse/LICENSE %{buildroot}/usr/share/package-licenses/kicad/1df9092b2b4fc9a252a18c729a9709a9c55d7308 || :
cp %{_builddir}/kicad-%{version}/thirdparty/clipper/LICENSE.BOOSTv1_0 %{buildroot}/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/kicad-%{version}/thirdparty/clipper2/LICENSE %{buildroot}/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/kicad-%{version}/thirdparty/compoundfilereader/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/4f1bc1f0e069a9385a59140b6fbaeea631addfc0 || :
cp %{_builddir}/kicad-%{version}/thirdparty/delaunator/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/5d45b543b1c2f5b45a04c4140b961862fd74c6e1 || :
cp %{_builddir}/kicad-%{version}/thirdparty/dxflib_qcad/LICENSE.GPLv2 %{buildroot}/usr/share/package-licenses/kicad/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/kicad-%{version}/thirdparty/fmt/LICENSE.rst %{buildroot}/usr/share/package-licenses/kicad/a6571b819c2fb290e2bb182e92a7a20d7d42318d || :
cp %{_builddir}/kicad-%{version}/thirdparty/glew/LICENSE.txt %{buildroot}/usr/share/package-licenses/kicad/0ca22faedb8ee495473a82c4d91452493b22ac9f || :
cp %{_builddir}/kicad-%{version}/thirdparty/gzip-hpp/LICENSE.BSD2 %{buildroot}/usr/share/package-licenses/kicad/5893f6b920ddec202044c789e4fd78d5177d8f5c || :
cp %{_builddir}/kicad-%{version}/thirdparty/json_schema_validator/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/f982f5b377a2cc00a04b1d4692a9dd81f15b22bb || :
cp %{_builddir}/kicad-%{version}/thirdparty/libcontext/LICENSE.BOOSTv1_0 %{buildroot}/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/kicad-%{version}/thirdparty/markdown2html/html_formatter/LICENSE.txt %{buildroot}/usr/share/package-licenses/kicad/33c0fbd4d001a07cc2e98c829e91fca5b28f3767 || :
cp %{_builddir}/kicad-%{version}/thirdparty/nanodbc/LICENSE %{buildroot}/usr/share/package-licenses/kicad/3664bdedb6035aefd386d0176ed8c8e9a724366f || :
cp %{_builddir}/kicad-%{version}/thirdparty/nanosvg/LICENSE.zlib %{buildroot}/usr/share/package-licenses/kicad/130fa43ba54e80bfa36404a32ba5e33e55d47d58 || :
cp %{_builddir}/kicad-%{version}/thirdparty/nlohmann_json/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/5aa6321f397c4409e3f8f6e26481aab583dccdf8 || :
cp %{_builddir}/kicad-%{version}/thirdparty/other_math/LICENSE.GPLv2 %{buildroot}/usr/share/package-licenses/kicad/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/kicad-%{version}/thirdparty/pegtl/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/kicad-%{version}/thirdparty/picosha2/LICENSE.MIT %{buildroot}/usr/share/package-licenses/kicad/54ccb5112da9a246ca18a4b9e795d859426dbbc1 || :
cp %{_builddir}/kicad-%{version}/thirdparty/potrace/LICENSE.GPLv2 %{buildroot}/usr/share/package-licenses/kicad/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/kicad-%{version}/thirdparty/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/kicad/3dbd61e2b2c71dcc658c3da90bacf2e15958075a || :
cp %{_builddir}/kicad-%{version}/thirdparty/rectpack2d/LICENSE %{buildroot}/usr/share/package-licenses/kicad/00c4f26d6c440cb90379e4c3bfef2abebc613d3f || :
cp %{_builddir}/kicad-%{version}/thirdparty/rtree/LICENSE.GPLv3 %{buildroot}/usr/share/package-licenses/kicad/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/LICENSE %{buildroot}/usr/share/package-licenses/kicad/8445285f7bd2c3d243e9425943011d6cc9beac0e || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/breakpad/LICENSE %{buildroot}/usr/share/package-licenses/kicad/743549aad1b10d93e1ed9c0048f06ddf1e21fd85 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/breakpad/src/third_party/curl/COPYING %{buildroot}/usr/share/package-licenses/kicad/d9249ffcf036ea6b7707403ae7ba967d5150fe30 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/breakpad/src/third_party/libdisasm/LICENSE %{buildroot}/usr/share/package-licenses/kicad/176f0f384fc922e443fdf1ced15f04d40566fb4f || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/breakpad/src/third_party/musl/COPYRIGHT %{buildroot}/usr/share/package-licenses/kicad/5c2f226413ffba59c4d89c54af4983ac763d2aa9 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/LICENSE %{buildroot}/usr/share/package-licenses/kicad/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/kicad/d79062af10a33188d4a74d976323845a2cf9023d || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/cpp-httplib/cpp-httplib/LICENSE %{buildroot}/usr/share/package-licenses/kicad/182c63f1b6debf67680a74898c8b97b4a6c496e4 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/lss/lss/LICENSE %{buildroot}/usr/share/package-licenses/kicad/aa45a6cf3b7bfcae7d6523f7d4e4818702dce7fe || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/mini_chromium/mini_chromium/LICENSE %{buildroot}/usr/share/package-licenses/kicad/1f7da163026124c7616e8ddde0ee336f141d08a5 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/mini_chromium/mini_chromium/base/third_party/icu/LICENSE %{buildroot}/usr/share/package-licenses/kicad/033ba4d37afbd624a0022253abf6241fd9f4d9f3 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/xnu/APPLE_LICENSE %{buildroot}/usr/share/package-licenses/kicad/f752e2ee8522bbdcd8945f73f6189958eb15a374 || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/crashpad/third_party/zlib/zlib/LICENSE %{buildroot}/usr/share/package-licenses/kicad/0f7174a2c02ad5a6951dcdca4a8c9acda981aa2e || :
cp %{_builddir}/kicad-%{version}/thirdparty/sentry-native/external/libunwindstack-ndk/LICENSE %{buildroot}/usr/share/package-licenses/kicad/472b23623e2c94dfe4b8b20e2b6ce2a3c4d54afd || :
cp %{_builddir}/kicad-%{version}/thirdparty/thread-pool/LICENSE.txt %{buildroot}/usr/share/package-licenses/kicad/a756af5a9d3559c55041727106fe24ca0bd47935 || :
cp %{_builddir}/kicad-%{version}/thirdparty/tinyspline_lib/LICENSE %{buildroot}/usr/share/package-licenses/kicad/44be17bcc7af43996c6fae52882dc02537e77ec2 || :
pushd clr-build
%make_install
popd
%find_lang kicad

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/_cvpcb.kiface
/usr/bin/_eeschema.kiface
/usr/bin/_gerbview.kiface
/usr/bin/_kipython.kiface
/usr/bin/_pcb_calculator.kiface
/usr/bin/_pcbnew.kiface
/usr/bin/_pl_editor.kiface
/usr/bin/bitmap2component
/usr/bin/dxf2idf
/usr/bin/eeschema
/usr/bin/gerbview
/usr/bin/idf2vrml
/usr/bin/idfcyl
/usr/bin/idfrect
/usr/bin/kicad
/usr/bin/kicad-cli
/usr/bin/pcb_calculator
/usr/bin/pcbnew
/usr/bin/pl_editor

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kicad.bitmap2component.desktop
/usr/share/applications/org.kicad.eeschema.desktop
/usr/share/applications/org.kicad.gerbview.desktop
/usr/share/applications/org.kicad.kicad.desktop
/usr/share/applications/org.kicad.pcbcalculator.desktop
/usr/share/applications/org.kicad.pcbnew.desktop
/usr/share/icons/hicolor/128x128/apps/bitmap2component.png
/usr/share/icons/hicolor/128x128/apps/eeschema.png
/usr/share/icons/hicolor/128x128/apps/gerbview.png
/usr/share/icons/hicolor/128x128/apps/kicad.png
/usr/share/icons/hicolor/128x128/apps/pcbcalculator.png
/usr/share/icons/hicolor/128x128/apps/pcbnew.png
/usr/share/icons/hicolor/128x128/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/128x128/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/128x128/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/16x16/apps/bitmap2component.png
/usr/share/icons/hicolor/16x16/apps/eeschema.png
/usr/share/icons/hicolor/16x16/apps/gerbview.png
/usr/share/icons/hicolor/16x16/apps/kicad.png
/usr/share/icons/hicolor/16x16/apps/pcbcalculator.png
/usr/share/icons/hicolor/16x16/apps/pcbnew.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/24x24/apps/bitmap2component.png
/usr/share/icons/hicolor/24x24/apps/eeschema.png
/usr/share/icons/hicolor/24x24/apps/gerbview.png
/usr/share/icons/hicolor/24x24/apps/kicad.png
/usr/share/icons/hicolor/24x24/apps/pcbcalculator.png
/usr/share/icons/hicolor/24x24/apps/pcbnew.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/32x32/apps/bitmap2component.png
/usr/share/icons/hicolor/32x32/apps/eeschema.png
/usr/share/icons/hicolor/32x32/apps/gerbview.png
/usr/share/icons/hicolor/32x32/apps/kicad.png
/usr/share/icons/hicolor/32x32/apps/pcbcalculator.png
/usr/share/icons/hicolor/32x32/apps/pcbnew.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/48x48/apps/bitmap2component.png
/usr/share/icons/hicolor/48x48/apps/eeschema.png
/usr/share/icons/hicolor/48x48/apps/gerbview.png
/usr/share/icons/hicolor/48x48/apps/kicad.png
/usr/share/icons/hicolor/48x48/apps/pcbcalculator.png
/usr/share/icons/hicolor/48x48/apps/pcbnew.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/64x64/apps/bitmap2component.png
/usr/share/icons/hicolor/64x64/apps/eeschema.png
/usr/share/icons/hicolor/64x64/apps/gerbview.png
/usr/share/icons/hicolor/64x64/apps/kicad.png
/usr/share/icons/hicolor/64x64/apps/pcbcalculator.png
/usr/share/icons/hicolor/64x64/apps/pcbnew.png
/usr/share/icons/hicolor/64x64/mimetypes/application-x-kicad-pcb.png
/usr/share/icons/hicolor/64x64/mimetypes/application-x-kicad-project.png
/usr/share/icons/hicolor/64x64/mimetypes/application-x-kicad-schematic.png
/usr/share/icons/hicolor/scalable/apps/bitmap2component.svg
/usr/share/icons/hicolor/scalable/apps/eeschema.svg
/usr/share/icons/hicolor/scalable/apps/gerbview.svg
/usr/share/icons/hicolor/scalable/apps/kicad.svg
/usr/share/icons/hicolor/scalable/apps/pcbcalculator.svg
/usr/share/icons/hicolor/scalable/apps/pcbnew.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-kicad-pcb.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-kicad-project.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-kicad-schematic.svg
/usr/share/kicad/demos/complex_hierarchy/ampli_ht.kicad_sch
/usr/share/kicad/demos/complex_hierarchy/complex_hierarchy.kicad_pcb
/usr/share/kicad/demos/complex_hierarchy/complex_hierarchy.kicad_pro
/usr/share/kicad/demos/complex_hierarchy/complex_hierarchy.kicad_sch
/usr/share/kicad/demos/complex_hierarchy/complex_hierarchy_schlib.kicad_sym
/usr/share/kicad/demos/complex_hierarchy/fp-lib-table
/usr/share/kicad/demos/complex_hierarchy/sym-lib-table
/usr/share/kicad/demos/custom_pads_test/custom_pads_schlib.kicad_sym
/usr/share/kicad/demos/custom_pads_test/custom_pads_test.kicad_pcb
/usr/share/kicad/demos/custom_pads_test/custom_pads_test.kicad_pro
/usr/share/kicad/demos/custom_pads_test/custom_pads_test.kicad_sch
/usr/share/kicad/demos/custom_pads_test/sym-lib-table
/usr/share/kicad/demos/ecc83/3d_shapes/ecc83.wrl
/usr/share/kicad/demos/ecc83/ecc83-pp.kicad_pcb
/usr/share/kicad/demos/ecc83/ecc83-pp.kicad_pro
/usr/share/kicad/demos/ecc83/ecc83-pp.kicad_sch
/usr/share/kicad/demos/ecc83/ecc83-pp_v2.kicad_pcb
/usr/share/kicad/demos/ecc83/ecc83-pp_v2.kicad_pro
/usr/share/kicad/demos/ecc83/ecc83-pp_v2.kicad_sch
/usr/share/kicad/demos/ecc83/ecc83_schlib.kicad_sym
/usr/share/kicad/demos/ecc83/footprints.pretty/MountingHole_3.2mm_M3_DIN965_Pad.kicad_mod
/usr/share/kicad/demos/ecc83/footprints.pretty/Valve_ECC-83-1.kicad_mod
/usr/share/kicad/demos/ecc83/footprints.pretty/Valve_ECC-83-2.kicad_mod
/usr/share/kicad/demos/ecc83/fp-lib-table
/usr/share/kicad/demos/ecc83/sym-lib-table
/usr/share/kicad/demos/electric/elec-unifil.kicad_sym
/usr/share/kicad/demos/electric/electric.kicad_pro
/usr/share/kicad/demos/electric/electric.kicad_sch
/usr/share/kicad/demos/electric/sym-lib-table
/usr/share/kicad/demos/flat_hierarchy/flat_hierarchy.kicad_pcb
/usr/share/kicad/demos/flat_hierarchy/flat_hierarchy.kicad_pro
/usr/share/kicad/demos/flat_hierarchy/flat_hierarchy.kicad_sch
/usr/share/kicad/demos/flat_hierarchy/fp-lib-table
/usr/share/kicad/demos/flat_hierarchy/libs/3d_shapes/adjustable_rx2v4.wrl
/usr/share/kicad/demos/flat_hierarchy/libs/flat_hierarchy_schlib.kicad_sym
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/D_DO-35_SOD27_P7.62mm_Horizontal.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/MountingHole_4.3mm_M4_DIN965.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/RV2X4.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/TO-220-3_Horizontal_TabDown.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/libs/pic_programmer_fp.pretty/TO-92.kicad_mod
/usr/share/kicad/demos/flat_hierarchy/pic_programmer.kicad_sch
/usr/share/kicad/demos/flat_hierarchy/pic_sockets.kicad_sch
/usr/share/kicad/demos/flat_hierarchy/sym-lib-table
/usr/share/kicad/demos/interf_u/fp-lib-table
/usr/share/kicad/demos/interf_u/interf_u.kicad_pcb
/usr/share/kicad/demos/interf_u/interf_u.kicad_pro
/usr/share/kicad/demos/interf_u/interf_u.kicad_sch
/usr/share/kicad/demos/interf_u/interf_u.pretty/BUS_PC.kicad_mod
/usr/share/kicad/demos/interf_u/interf_u.pretty/PGA120.kicad_mod
/usr/share/kicad/demos/interf_u/interf_u.pretty/tux.kicad_mod
/usr/share/kicad/demos/interf_u/interf_u_schlib.kicad_sym
/usr/share/kicad/demos/interf_u/pagelayout_logo.kicad_wks
/usr/share/kicad/demos/interf_u/sym-lib-table
/usr/share/kicad/demos/interf_u/tux.bmp
/usr/share/kicad/demos/interf_u/tux.kicad_sym
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/fp-lib-table
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/in_out_conn.kicad_sch
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-coldfire_schlib.kicad_sym
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire-xilinx_5213.kicad_pcb
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire-xilinx_5213.kicad_pro
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire-xilinx_5213.kicad_sch
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/FSUPCMS.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/JACK_ALIM.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/SM1206POL.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/SOT23EBC.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/SOT353.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/SW_PUSH_SMALL.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/kit-dev-coldfire.pretty/SW_SPDT.kicad_mod
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/Device.switch_toggle_horizontal_right_angle_PC_terminal.wings
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/Device.switch_toggle_horizontal_right_angle_PC_terminal.wrl
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/Jack.wings
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/Jack.wrl
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/db9_female_pin90deg.wrl
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/push_butt_4pads.wings
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/prj.3dshapes/push_butt_4pads.wrl
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/sym-lib-table
/usr/share/kicad/demos/kit-dev-coldfire-xilinx_5213/xilinx.kicad_sch
/usr/share/kicad/demos/microwave/microwave.kicad_pcb
/usr/share/kicad/demos/microwave/microwave.kicad_pro
/usr/share/kicad/demos/microwave/shape1.txt
/usr/share/kicad/demos/pic_programmer/fp-lib-table
/usr/share/kicad/demos/pic_programmer/libs/3d_shapes/adjustable_rx2v4.wrl
/usr/share/kicad/demos/pic_programmer/libs/3d_shapes/textool_40.wrl
/usr/share/kicad/demos/pic_programmer/libs/pic_programmer_fp.pretty/40tex-Ell600.kicad_mod
/usr/share/kicad/demos/pic_programmer/libs/pic_programmer_fp.pretty/RV2X4.kicad_mod
/usr/share/kicad/demos/pic_programmer/libs/pic_programmer_schlib.kicad_sym
/usr/share/kicad/demos/pic_programmer/pic_programmer.kicad_pcb
/usr/share/kicad/demos/pic_programmer/pic_programmer.kicad_pro
/usr/share/kicad/demos/pic_programmer/pic_programmer.kicad_sch
/usr/share/kicad/demos/pic_programmer/pic_sockets.kicad_sch
/usr/share/kicad/demos/pic_programmer/sym-lib-table
/usr/share/kicad/demos/python_scripts_examples/action_menu_add_automatic_border.py
/usr/share/kicad/demos/python_scripts_examples/action_menu_text_by_date.py
/usr/share/kicad/demos/python_scripts_examples/action_plugin_test_undoredo.py
/usr/share/kicad/demos/python_scripts_examples/gen_gerber_and_drill_files_board.py
/usr/share/kicad/demos/python_scripts_examples/plot_board.py
/usr/share/kicad/demos/simulation/laser_driver/ad8009.lib
/usr/share/kicad/demos/simulation/laser_driver/fzt1049a.lib
/usr/share/kicad/demos/simulation/laser_driver/laser.lib
/usr/share/kicad/demos/simulation/laser_driver/laser_driver.kicad_pro
/usr/share/kicad/demos/simulation/laser_driver/laser_driver.kicad_sch
/usr/share/kicad/demos/simulation/laser_driver/laser_driver_schlib.kicad_sym
/usr/share/kicad/demos/simulation/laser_driver/sym-lib-table
/usr/share/kicad/demos/simulation/pspice/pspice.kicad_pro
/usr/share/kicad/demos/simulation/pspice/pspice.kicad_sch
/usr/share/kicad/demos/simulation/pspice/schematic_libspice.kicad_sym
/usr/share/kicad/demos/simulation/pspice/sym-lib-table
/usr/share/kicad/demos/simulation/rectifier/diode.mod
/usr/share/kicad/demos/simulation/rectifier/rectifier.kicad_pro
/usr/share/kicad/demos/simulation/rectifier/rectifier.kicad_sch
/usr/share/kicad/demos/simulation/rectifier/rectifier_schlib.kicad_sym
/usr/share/kicad/demos/simulation/rectifier/sym-lib-table
/usr/share/kicad/demos/simulation/sallen_key/ad8051.lib
/usr/share/kicad/demos/simulation/sallen_key/sallen_key.kicad_pro
/usr/share/kicad/demos/simulation/sallen_key/sallen_key.kicad_sch
/usr/share/kicad/demos/simulation/sallen_key/sallen_key_schlib.kicad_sym
/usr/share/kicad/demos/simulation/sallen_key/sym-lib-table
/usr/share/kicad/demos/simulation/subsheets/subsheet1.kicad_sch
/usr/share/kicad/demos/simulation/subsheets/subsheet2.kicad_sch
/usr/share/kicad/demos/simulation/subsheets/subsheets.kicad_sch
/usr/share/kicad/demos/simulation/v_i_sources/sym-lib-table
/usr/share/kicad/demos/simulation/v_i_sources/v_i_sources.kicad_pro
/usr/share/kicad/demos/simulation/v_i_sources/v_i_sources.kicad_sch
/usr/share/kicad/demos/simulation/v_i_sources/v_i_sources.kicad_sym
"/usr/share/kicad/demos/sonde xilinx/fp-lib-table"
"/usr/share/kicad/demos/sonde xilinx/sonde xilinx.kicad_pcb"
"/usr/share/kicad/demos/sonde xilinx/sonde xilinx.kicad_pro"
"/usr/share/kicad/demos/sonde xilinx/sonde xilinx.kicad_sch"
"/usr/share/kicad/demos/sonde xilinx/sonde_xilinx_schlib.kicad_sym"
"/usr/share/kicad/demos/sonde xilinx/sym-lib-table"
/usr/share/kicad/demos/stickhub/3dmodels/APHB1608.step
/usr/share/kicad/demos/stickhub/3dmodels/Crystal_SMD_4P_2520.step
/usr/share/kicad/demos/stickhub/3dmodels/JST_SH_SM04B-SRSS-TB.STEP
/usr/share/kicad/demos/stickhub/3dmodels/TDFN-8_1.5x2mm_Fused-Lead_MO-252-W2015D.step
/usr/share/kicad/demos/stickhub/LICENSE.md
/usr/share/kicad/demos/stickhub/README.md
/usr/share/kicad/demos/stickhub/RobotProtos.kicad_sym
/usr/share/kicad/demos/stickhub/StickHub.kicad_pcb
/usr/share/kicad/demos/stickhub/StickHub.kicad_pro
/usr/share/kicad/demos/stickhub/StickHub.kicad_sch
/usr/share/kicad/demos/stickhub/footprints.pretty/1005_C.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/1006_C.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/1608_C.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/1P-1.5x1.5.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/2012_C.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/CP_Elec_6.3x11_Board_Edge_Mirrored.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Creative_Commons_BY_Mask.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Creative_Commons_CC_Mask.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Creative_Commons_NC_Mask.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Creative_Commons_SA_Mask.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Crystal_4-SMD_2.5x2mm.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Duo_LED_1.6x0.8_Kingbright_APHB1608LZGKSURKC.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/JP-2_1.5x1.5.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/LQFP-48_7x7mm_P0.5mm.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/Plain_Hole_3mm.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/TDFN-8_1.5x2mm_Fused-Lead_JEDEC_MO-252_W2015D.kicad_mod
/usr/share/kicad/demos/stickhub/footprints.pretty/USB_A_PCB_traces_small.kicad_mod
/usr/share/kicad/demos/stickhub/fp-lib-table
/usr/share/kicad/demos/stickhub/sym-lib-table
/usr/share/kicad/demos/test_pads_inside_pads/connect.pretty/1pin.kicad_mod
/usr/share/kicad/demos/test_pads_inside_pads/connect.pretty/1pin_thermal.kicad_mod
/usr/share/kicad/demos/test_pads_inside_pads/fp-lib-table
/usr/share/kicad/demos/test_pads_inside_pads/sym-lib-table
/usr/share/kicad/demos/test_pads_inside_pads/test_pads_inside_pads.kicad_pcb
/usr/share/kicad/demos/test_pads_inside_pads/test_pads_inside_pads.kicad_pro
/usr/share/kicad/demos/test_pads_inside_pads/test_pads_inside_pads.kicad_sch
/usr/share/kicad/demos/test_pads_inside_pads/test_pads_inside_pads_schlib.kicad_sym
/usr/share/kicad/demos/test_xil_95108/carte_test.kicad_pcb
/usr/share/kicad/demos/test_xil_95108/carte_test.kicad_pro
/usr/share/kicad/demos/test_xil_95108/carte_test.kicad_sch
/usr/share/kicad/demos/test_xil_95108/carte_test_schlib.kicad_sym
/usr/share/kicad/demos/test_xil_95108/footprints.pretty/DIP-28__300__600_ELL.kicad_mod
/usr/share/kicad/demos/test_xil_95108/footprints.pretty/PLCC84.kicad_mod
/usr/share/kicad/demos/test_xil_95108/fp-lib-table
/usr/share/kicad/demos/test_xil_95108/sym-lib-table
/usr/share/kicad/demos/video/bus_pci.kicad_sch
/usr/share/kicad/demos/video/esvideo.kicad_sch
/usr/share/kicad/demos/video/fp-lib-table
/usr/share/kicad/demos/video/graphic.kicad_sch
/usr/share/kicad/demos/video/libs/footprints.pretty/BUSPCI.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/CV3-30PF.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/D_DO-34_SOD68_P7.62mm_Horizontal.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/LED_D3.0mm.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/LRTDK.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/PLCC68.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/PLCC84.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/SOT23EBC.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/SolderJumper-2_P1.3mm_Open_Pad1.0x1.5mm.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/sim72.kicad_mod
/usr/share/kicad/demos/video/libs/footprints.pretty/subclick.kicad_mod
/usr/share/kicad/demos/video/libs/fp.3dshapes/subclick_horiz.wings
/usr/share/kicad/demos/video/libs/fp.3dshapes/subclick_horiz.wrl
/usr/share/kicad/demos/video/libs/video_schlib.kicad_sym
/usr/share/kicad/demos/video/modul.kicad_sch
/usr/share/kicad/demos/video/muxdata.kicad_sch
/usr/share/kicad/demos/video/pal-ntsc.kicad_sch
/usr/share/kicad/demos/video/rams.kicad_sch
/usr/share/kicad/demos/video/sym-lib-table
/usr/share/kicad/demos/video/video.kicad_pcb
/usr/share/kicad/demos/video/video.kicad_pro
/usr/share/kicad/demos/video/video.kicad_sch
/usr/share/kicad/plugins/README-bom.txt
/usr/share/kicad/plugins/bom_csv_grouped_by_value.py
/usr/share/kicad/plugins/bom_csv_grouped_by_value_with_fp.py
/usr/share/kicad/plugins/bom_csv_grouped_extra.py
/usr/share/kicad/plugins/bom_csv_sorted_by_ref.py
/usr/share/kicad/plugins/bom_html_grouped_by_value.py
/usr/share/kicad/plugins/bom_html_with_advanced_grouping.py
/usr/share/kicad/plugins/bom_txt_sorted_by_ref.py
/usr/share/kicad/plugins/kicad_netlist_reader.py
/usr/share/kicad/plugins/kicad_utils.py
/usr/share/kicad/resources/images.tar.gz
/usr/share/kicad/schemas/pcm.v1.schema.json
/usr/share/kicad/scripting/kicad_pyshell/__init__.py
/usr/share/kicad/scripting/kicad_pyshell/kicad_pyeditor.py
/usr/share/kicad/scripting/plugins/FPC_wizard.py
/usr/share/kicad/scripting/plugins/FootprintWizardBase.py
/usr/share/kicad/scripting/plugins/PadArray.py
/usr/share/kicad/scripting/plugins/__init__.py
/usr/share/kicad/scripting/plugins/arc_test.py
/usr/share/kicad/scripting/plugins/bga_wizard.py
/usr/share/kicad/scripting/plugins/circular_pad_array_wizard.py
/usr/share/kicad/scripting/plugins/kicad_qrcode.py
/usr/share/kicad/scripting/plugins/microMatch_connectors.py
/usr/share/kicad/scripting/plugins/mutualcap_button_wizard.py
/usr/share/kicad/scripting/plugins/qfn_wizard.py
/usr/share/kicad/scripting/plugins/qfp_wizard.py
/usr/share/kicad/scripting/plugins/qrcode_footprint_wizard.py
/usr/share/kicad/scripting/plugins/sdip_wizard.py
/usr/share/kicad/scripting/plugins/touch_slider_wizard.py
/usr/share/kicad/scripting/plugins/uss39_barcode.py
/usr/share/kicad/scripting/plugins/zip_wizard.py
/usr/share/kicad/template/kicad.kicad_pro
/usr/share/metainfo/org.kicad.kicad.metainfo.xml
/usr/share/mime-packages/kicad-gerbers.xml
/usr/share/mime-packages/kicad-kicad.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkicad_3dsg.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/kicad/plugins/3d/libs3d_plugin_idf.so
/usr/lib64/kicad/plugins/3d/libs3d_plugin_oce.so
/usr/lib64/kicad/plugins/3d/libs3d_plugin_vrml.so
/usr/lib64/libkicad_3dsg.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kicad/00c4f26d6c440cb90379e4c3bfef2abebc613d3f
/usr/share/package-licenses/kicad/033ba4d37afbd624a0022253abf6241fd9f4d9f3
/usr/share/package-licenses/kicad/0ca22faedb8ee495473a82c4d91452493b22ac9f
/usr/share/package-licenses/kicad/0f7174a2c02ad5a6951dcdca4a8c9acda981aa2e
/usr/share/package-licenses/kicad/130fa43ba54e80bfa36404a32ba5e33e55d47d58
/usr/share/package-licenses/kicad/176f0f384fc922e443fdf1ced15f04d40566fb4f
/usr/share/package-licenses/kicad/182c63f1b6debf67680a74898c8b97b4a6c496e4
/usr/share/package-licenses/kicad/1df9092b2b4fc9a252a18c729a9709a9c55d7308
/usr/share/package-licenses/kicad/1f7da163026124c7616e8ddde0ee336f141d08a5
/usr/share/package-licenses/kicad/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/kicad/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/kicad/33c0fbd4d001a07cc2e98c829e91fca5b28f3767
/usr/share/package-licenses/kicad/3664bdedb6035aefd386d0176ed8c8e9a724366f
/usr/share/package-licenses/kicad/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/kicad/3dbd61e2b2c71dcc658c3da90bacf2e15958075a
/usr/share/package-licenses/kicad/44be17bcc7af43996c6fae52882dc02537e77ec2
/usr/share/package-licenses/kicad/472b23623e2c94dfe4b8b20e2b6ce2a3c4d54afd
/usr/share/package-licenses/kicad/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/kicad/4f1bc1f0e069a9385a59140b6fbaeea631addfc0
/usr/share/package-licenses/kicad/534d2a4a032e36089b075fcea7c5fa824b68f2f6
/usr/share/package-licenses/kicad/54ccb5112da9a246ca18a4b9e795d859426dbbc1
/usr/share/package-licenses/kicad/5893f6b920ddec202044c789e4fd78d5177d8f5c
/usr/share/package-licenses/kicad/5aa6321f397c4409e3f8f6e26481aab583dccdf8
/usr/share/package-licenses/kicad/5ade1f53777ddcabcbc4638e550155c97825db30
/usr/share/package-licenses/kicad/5c2f226413ffba59c4d89c54af4983ac763d2aa9
/usr/share/package-licenses/kicad/5d45b543b1c2f5b45a04c4140b961862fd74c6e1
/usr/share/package-licenses/kicad/743549aad1b10d93e1ed9c0048f06ddf1e21fd85
/usr/share/package-licenses/kicad/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kicad/8445285f7bd2c3d243e9425943011d6cc9beac0e
/usr/share/package-licenses/kicad/8a1a0366d77ee3af93e9f1a6c5c14526be2d1e50
/usr/share/package-licenses/kicad/a6571b819c2fb290e2bb182e92a7a20d7d42318d
/usr/share/package-licenses/kicad/a756af5a9d3559c55041727106fe24ca0bd47935
/usr/share/package-licenses/kicad/aa45a6cf3b7bfcae7d6523f7d4e4818702dce7fe
/usr/share/package-licenses/kicad/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/kicad/d9249ffcf036ea6b7707403ae7ba967d5150fe30
/usr/share/package-licenses/kicad/f752e2ee8522bbdcd8945f73f6189958eb15a374
/usr/share/package-licenses/kicad/f982f5b377a2cc00a04b1d4692a9dd81f15b22bb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f kicad.lang
%defattr(-,root,root,-)

